[project]
name = "rfm95-receiver"
version = "0.1.0"
description = "Yard.net RFM95 receiver for LoRaWAN devices"
authors = [
    { name = "Tom-Camp", email = "tomcamp@protonmail.ch" },
]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "adafruit-blinka",
    "adafruit-circuitpython-rfm9x",
    "httpx",
    "loguru",
    "msgpack>=1.1.2",
    "pydantic-settings",
    "tenacity",
]
